### ISSUE TITLE
[Docs] Update docs with readout error mitigation techniques

### ISSUE THREAD

**Issue by RolandMacDoland** [pasqal-io/qadence-protocols#24]
There is a number of readout error mitigation techniques implemented by @rajaiitp and @gvelikova . It would be good to update docs acccordingly.

**Comment by RolandMacDoland** [comment]
@rajaiitp @gvelikova Would you guys have time to pick that up ? That'd be great. Thanks

**Comment by rajaiitp** [comment]
Just got back from a long vacation, I will start working on this
