### ISSUE TITLE
Implement model-free readout error mitigation

### ISSUE THREAD

**Issue by RolandMacDoland** [pasqal-io/qadence-protocols#5]
@gvelikova @rajaiitp Please add a description and link it to the current PR.

**Comment by RolandMacDoland** [comment]
Moved comments:

@[gvelikova](https://github.com/gvelikova) gvelikova [5 days ago](https://github.com/pasqal-io/qadence-protocols/pull/3#discussion_r1464637655)
Can these be taken out as yet another helper function that can take as arguments the specific _den or _num variables?

Collaborator
@[gvelikova](https://github.com/gvelikova) gvelikova [5 days ago](https://github.com/pasqal-io/qadence-protocols/pull/3#discussion_r1464638390)
Lines 68-73 and 75-80.

Collaborator
@[rajaiitp](https://github.com/rajaiitp) rajaiitp [5 days ago](https://github.com/pasqal-io/qadence-protocols/pull/3#discussion_r1464752033)
Yup, was thinking of the same. But it just runs the circuit with a specific configuration and returns samples, so writing a function seems like an overkill. I can write a for loop, but not sure if its worth it with just 2 different configs and 5 lines of code. I will wait for @Roland-djee to decide which of the 2 would be better.

Collaborator
@[rajaiitp](https://github.com/rajaiitp) rajaiitp [4 days ago](https://github.com/pasqal-io/qadence-protocols/pull/3#discussion_r1466144552)
@Roland-djee i have not changed this. Let me know what you think.

**Comment by RolandMacDoland** [comment]
The observables are not specified in the standard fashion. This needs to be changed, but idk how to manipulate them to retrieve index locations and coefficients of each pauli term when written in that fashion

The protocol runs only for diagonal observables as measurements make only sense in this basis. I have not put these checks in place. For other cases one needs to include basis rotations as a part of the circuit and evaluate those circuits independently. (true for any readout mitigation protocol)

Not sure what the arguments need to be, should it be at the level of circuit or model

Measurement of samples from observables has been written thru some homemade hacky code. Maybe have it on qadence at the level of circuit or model ?

**Comment by RolandMacDoland** [comment]
Hey @rajaiitp, thank you for this. Before going further, I would suggest few main points:

Use the current infra in place in Qadence (essentially [this file](https://github.com/pasqal-io/qadence/blob/main/qadence/mitigations/protocols.py)). Because it makes for a better interface and we might what to pass options to mitigation protocols.
Maybe we should think about what object needs to be passed to the mitigation function. I don't think that
expectation_mitigated = twirl_mitigation(n_qubits, circuit, backend, noise, n_shots, observable)
is very useful nor generic. What about passing model and noise objects ? WOuld that be enough ?

**Comment by RolandMacDoland** [comment]
Passing model, noise and observable should be enough, thou i need to extract the circuit blocks back again and reconstruct the circuit with changes made to the end.
I am not passing observable the standard way, so that needs to fixed. It can be fixed only after qadence allows to compute expectation values from samples I think. So need that to be done first.
I will push my current changes and then work on the interfacing to look like qadence following that.
I presume the model structure is meant for training. Shouldnt we work at the circuit level for sampling and expectation values ?

**Comment by RolandMacDoland** [comment]
@[Roland-djee](https://github.com/Roland-djee) Roland-djee Pending
The tensor type in pytorch is Tensor.

**Comment by RolandMacDoland** [comment]
@rajaiitp I would suggest you to develop along these lines:

```python
model = QuantumModel(...) <-- to hold circuit, backend, noise etc
mitigate = Mitigations(Mitigations.TWIRL).mitigate() <-- returns a function
mitigated_vals = mitigate(model)
```

**Comment by RolandMacDoland** [comment]
Also: please allow passing samples through `options` if you need to apply mitigations to ready made samples.

**Comment by rajaiitp** [comment]
Closing this one as its completed and merged
